### ISSUE TITLE
Enable search

### ISSUE THREAD

**Issue by imiric** [FriendlyCaptcha/friendly-docs#22]
Currently we don't have search functionality in the docs site, which would be very useful.

[Docusaurus supports it with various methods](https://docusaurus.io/docs/search), so let's look into what would work best for us.

We don't have a lot of documentation, so hopefully a local on-device index would be feasible. Otherwise let's consider one of the alternatives.

**Comment by greenberga** [comment]
I think we'd [qualify for Algolia](https://docsearch.algolia.com/docs/who-can-apply/), so that's an option too. But it would be nice not to have to do a network call for searching and keep things more offline-friendly. One of [the community search plugins](https://docusaurus.io/community/resources#search) could be a possibility.
